# Generated by Django 3.1.4 on 2021-01-15 11:22

from django.db import migrations
import users.formatchecker


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=users.formatchecker.ContentTypeRestrictedFileField(blank=True, null=True, upload_to='users/uploads/%Y/%m/%d/'),
        ),
    ]
