# Generated by Django 3.1.4 on 2021-01-15 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='newsimage',
            options={'verbose_name': 'News images', 'verbose_name_plural': 'News images'},
        ),
    ]
