<<<<<<< HEAD
# Generated by Django 3.1.4 on 2021-01-20 12:25

from django.conf import settings
=======
# Generated by Django 3.1.4 on 2021-01-12 09:28

>>>>>>> e8c7acc5d40449e929e78e32019c72921639da13
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> e8c7acc5d40449e929e78e32019c72921639da13
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_type', models.CharField(max_length=64)),
                ('article_value', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ClothingSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothing_type', models.CharField(max_length=64)),
                ('clothing_value', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('excel_file', models.FileField(upload_to='excel_files')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
                ('excel_file', models.FileField(upload_to='')),
>>>>>>> e8c7acc5d40449e929e78e32019c72921639da13
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tnved', models.CharField(max_length=64)),
                ('full_product_name', models.CharField(max_length=128)),
                ('trademark', models.CharField(max_length=64)),
                ('product_type', models.CharField(max_length=64)),
                ('color', models.CharField(max_length=64)),
                ('target_gender', models.CharField(max_length=64)),
                ('composition', models.CharField(max_length=64)),
                ('standard_no', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=64)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.article')),
                ('clothing_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.clothingsize')),
<<<<<<< HEAD
                ('excel_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.excelfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
>>>>>>> e8c7acc5d40449e929e78e32019c72921639da13
            ],
        ),
    ]
