# Generated by Django 3.1.5 on 2021-02-05 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfile',
            name='file_name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
