# Generated by Django 3.1.4 on 2021-01-15 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='excel_file',
        ),
    ]
