# Generated by Django 3.1.5 on 2021-02-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_excelfile_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelfiletemplate',
            name='file_name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
